force-app/main/default/objects/ExternalSource__mdt/ExternalSource__mdt.object-meta.xml
<CustomObject>
    <label>External Source</label>
    <pluralLabel>External Sources</pluralLabel>
</CustomObject>

force-app/main/default/objects/ExternalSource__mdt/fields/AccessKey__c.field-meta.xml
<CustomField>
    <fullName>AccessKey__c</fullName>
    <label>Access Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ExternalSource__mdt/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <label>Endpoint</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/CustomMetadataSelector.cls
public class CustomMetadataSelector implements API
{
	public interface API
	{
		ExternalSource__mdt selectExternalResource();
	}

	@TestVisible
	private static API instance;

	public static API getInstance()
	{
		if (instance == null)
			instance = new CustomMetadataSelector();

		return instance;
	}

	public ExternalSource__mdt selectExternalResource()
	{
		return [SELECT AccessKey__c, Endpoint__c FROM ExternalSource__mdt][0];
	}
}