force-app/main/default/objects/Trade__c/Trade__c.object-meta.xml
<CustomObject>
    <label>Trade</label>
    <nameField>
        <displayFormat>TR{0000000}</displayFormat>
        <label>Trade Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trade__c/fields/BuyAmount__c.field-meta.xml
<CustomField>
    <fullName>BuyAmount__c</fullName>
    <label>Buy Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/BuyCurrency__c.field-meta.xml
<CustomField>
    <fullName>BuyCurrency__c</fullName>
    <label>Buy Currency</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>9</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/SellAmount__c.field-meta.xml
<CustomField>
    <fullName>SellAmount__c</fullName>
    <label>Sell Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/SellCurrency__c.field-meta.xml
<CustomField>
    <fullName>SellCurrency__c</fullName>
    <label>Sell Currency</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Trades.cls
public class Trades
{
	private static final String GROUP_NAME = 'Trade reviewers';

	public static void handleAfterInsert(List<SObject> newRecords)
	{
		CollaborationGroup chatterGroup = getGroup();
		List<FeedItem> newFeedItems = new List<FeedItem>();

		for (Trade__c newTrade : (List<Trade__c>) newRecords)
		{
			FeedItem newFeedItem = new FeedItem();

			newFeedItem.Body = buildMessage(newTrade);
			newFeedItem.ParentId = chatterGroup.Id;

			newFeedItems.add(newFeedItem);
		}

		insert newFeedItems;
	}

	private static CollaborationGroup getGroup()
	{
		List<CollaborationGroup> groups = GroupSelector.getInstance().selectQueueByName(GROUP_NAME);
		if (groups.isEmpty())
		{
			CollaborationGroup newGroup = new CollaborationGroup();
			newGroup.Name = GROUP_NAME;
			newGroup.CollaborationType = 'Public';

			insert newGroup;
			return newGroup;
		}

		return groups[0];
	}

	private static String buildMessage(Trade__c newTrade)
	{
		String sellCurrency = newTrade.SellCurrency__c;
		String sellAmount = String.valueOf(newTrade.SellAmount__c);
		String buyCurrency = newTrade.BuyCurrency__c;
		String buyAmount = String.valueOf(newTrade.BuyAmount__c);
		String rate = String.valueOf(newTrade.Rate__c);
		String createdDate = String.valueOf(newTrade.CreatedDate);
		String linkTrade = URL.getSalesforceBaseUrl().toExternalForm() + '/' + newTrade.Id;

		return String.format(Label.ChatterMessageNewTrade, new List<String> { sellCurrency, sellAmount, buyCurrency, buyAmount, rate, createdDate, linkTrade });
	}
}